version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: hms_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: hms_db_1
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - hms_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb://admin:admin_password@localhost:27017/admin
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  api:
    build: .
    container_name: hms_api
    environment:
      - MONGODB_URL=mongodb://admin:admin_password@mongodb:27017/hms_db_1?authSource=admin
      - DATABASE_NAME=hms_db_1
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - hms_network
    restart: on-failure

networks:
  hms_network:
    driver: bridge

volumes:
  mongodb_data: